version: '3.8'

services:
  backend:
    build: backend
    hostname: backend
    ports:
      - "5000:5000"
    networks:
      - docknodex-net

  frontend:
    build: frontend
    hostname: frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://backend:5000/api
    depends_on:
      - backend
    networks:
      - docknodex-net

networks:
  docknodex-net: {}
